#!/bin/sh
#
# chkconfig: 2345 90 10
#
# Custom script for managing mongodb.
# This abstracts away starting/stopping the multiple mongod instances
# we require.
#
# To have the mongo processes start automatically (as root), copy this
# file into /etc/init.d, and run:
# $ sudo chkconfig --add mongo_cntrl
#
# From then on, it will start on reboot, and can be managed using
# sudo service mongo_cntrl (restart|start|stop)
#

start() {
    echo "Setting up log and data directories"
    mkdir -p /home/rmc/logs/mongo
    mkdir -p /home/rmc/data/mongo
    echo "Starting mongodb on default port with dbpath /home/rmc/data/mongo"
    # Note - default mongo port 27017
    /usr/bin/mongod --config /home/rmc/rmc/config/mongodb_prod.conf
}
stop() {
    echo "Killing all mongod processes"

    # Will error if none are found, but that's OK.
    killall mongod 2> /dev/null
}
restart() {
  stop
  start
}
# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    echo "Does not apply"
    ;;
  restart)
    restart
    ;;
  condrestart|try-restart)
    restart
    ;;
  reload)
    restart
    ;;
  force-reload)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
    exit 2
esac

exit $?
