# define cross file constants here

MONGO_HOST = 'localhost'
MONGO_PORT = 27017
MONGO_DB_RMC = 'rmc'

REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0

OPENDATA_COURSES_DATA_DIR = 'opendata_courses'
UWDATA_COURSES_DATA_DIR = 'uwdata_courses'
REVIEWS_DATA_DIR = 'reviews'
DEPARTMENTS_DATA_DIR = 'departments'

COURSE_REVIEW_FIELD_EASINESS = 'easiness'
COURSE_REVIEW_FIELD_INTEREST = 'interest'
COURSE_REVIEW_FIELD_USEFULNESS = 'usefulness'

PROFESSOR_REVIEW_FIELD_CLARITY = 'clarity'
PROFESSOR_REVIEW_FIELD_PASSION = 'passion'
