class PointSource(object):
    FIRST_INVITE = 100
    COURSE_COMMENT = 50
    COURSE_RATING = 10
    SHARE_COURSE_REVIEW = 50
    PROFESSOR_COMMENT = 50
    PROFESSOR_RATING = 10
    SHARE_PROFESSOR_REVIEW = 50
